### ISSUE TITLE
When /hat is a block that can be converted using /block it dupes

### ISSUE THREAD

**Issue by iMaarten** [aaomidi/BlockCreator#1]
I just noticed a bug with the /block and /hat commands on prison. 
In the beginning, I have no emeralds in my inventory or /hat and /block doesn’t work, obviously. Then a bit later I put a couple of emeralds as /hat and uses the block command again and it gives me free emerald blocks without taking anything from me. And I can sell them so it’s not a visual glitch. 

Version: 1.12.2

Vid: https://www.youtube.com/watch?v=s82kdGJARus

**Comment by aaomidi** [comment]
Thanks for reporting the bug!

**Comment by aaomidi** [comment]
https://github.com/aaomidi/BlockCreator/commit/e4df48d1c65ab7d481ceb270e4d53a1b89c411da

Please reopen this issue if the problem isn't solved.
